snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%env(REDIS_URL)%"
        local:
            type: phpredis
            alias: local
            dsn: "%env(REDIS_LOCAL_URL)%"
