<?php declare(strict_types=1);

use App\Page\Component\BackgroundImage\BackgroundImageComponent;

/**
 * @var BackgroundImageComponent $this
 */
?>
<div class="row">
    <div class="col-12" style="
            background-color: <?= $this->backgroundColor; ?>;
            background-repeat: no-repeat;
            background-size: cover;
    <?php if (!empty($this->backgroundImage)): ?>
            background-image: url(<?= $this->backgroundImage; ?>);
    <?php endif; ?>
            ">
        <?php echo $this->content->render(); ?>
    </div>
</div>
