monolog:
    channels: ['api']
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            formatter: monolog.formatter.application
            level: debug
            channels: ["!event","!api"]
            max_files: 60

        console:
            type: console
            formatter: monolog.formatter.application
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
