version: '3.4'

services:

  wcas-web:
    image: wcas-local
    container_name: "${APP_CONTAINER_NAME}_web"
    ports:
      - "${APP_CONTAINER_PORT}:8080"
    volumes:
      - ../.env.docker:/var/www/html/.env

  wcas-scheduler:
    image: wcas-local
    container_name: "${APP_CONTAINER_NAME}_scheduler"
    volumes:
      - ../.env.docker:/var/www/html/.env
    command: /docker_entrypoint.sh scheduler

  wcas-mysql:
    image: mysql:8.0
    container_name: "${APP_CONTAINER_NAME}_mysql"
    environment:
      MYSQL_USER: wcas
      MYSQL_PASSWORD: h3vd993kdp
      MYSQL_DATABASE: wcas_db
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ../docker/var/mysql_data:/var/lib/mysql

  wcas-redis:
    image: redis:alpine
    container_name: "${APP_CONTAINER_NAME}_redis"
