version: '3.4'

services:

  tusi-web:
    image: tusi-local
    container_name: "${APP_CONTAINER_NAME}_web"
    ports:
      - "${APP_CONTAINER_PORT}:80"
    volumes:
      - ../.env.docker:/var/www/html/.env

  tusi-scheduler:
    image: tusi-local
    container_name: "${APP_CONTAINER_NAME}_scheduler"
    volumes:
      - ../.env.docker:/var/www/html/.env
    command: /docker_entrypoint.sh scheduler

  tusi-mysql:
    image: mysql:8.0
    container_name: "${APP_CONTAINER_NAME}_mysql"
    environment:
      MYSQL_USER: tusi
      MYSQL_PASSWORD: h3vd993kdp
      MYSQL_DATABASE: tusi_db
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ../docker/var/mysql_data:/var/lib/mysql
