<?php declare(strict_types=1);

use App\Page\Component\YouTube\YouTubeComponent;

/**
 * @var YouTubeComponent $this
 */
?>

<div class="yt-container">
    <iframe src="<?php echo $this->getEmbedUrl(); ?>"
            allow="autoplay; encrypted-media"
            class="yt-content"
            width="100%"
            height="100%"
            allowfullscreen>
    </iframe>
</div>

<style>
    .yt-container {
        position: relative;
        width:    100%;
    }
    .yt-container:before {
        content:     "";
        display:     block;
        padding-top: 58%;
    }
    .yt-content {
        position: absolute;
        top:      0;
        left:     0;
        bottom:   0;
        right:    0;
    }

</style>


